### ISSUE TITLE
Timer Stuck

### ISSUE THREAD

**Issue by Clank50AE** [MapleLeafMakers/KlipperMacros#4]
Not sure what is going on with the code but the timer is stuck at 1.11 hours. I've printed a good deal more than that with it

**Comment by MapleLeafMakers** [comment]
Without more information I can only make a few suggestions:

 - restart klipper?
 - confirm the `variable_fan` setting in air_filter_timer.cfg matches your configuration for the air filter
 - check the klippy.log for any relevant errors
 - check that the file you configured for saved_variables is writable by the klipper process, maybe try deleting it
 - try adding some M118 commands to the macros to print out messages to confirm they're running as they should

if you want to upload a klippy.log after running the filter for a few minutes that might help too
 
also keep in mind it doesn't track print time, it only counts the time the filter is actively filtering.

**Comment by Clank50AE** [comment]
Thank you for your response! I wasn't expecting one this fast. I'll look at all those things you suggested. Im away it only tracks time that the chamber fan is running. Once this print ends, I'll check the log and upload it. I'm printing on a Qiditech Q1 Pro with a nevermore V6 installed. It's running stock firmware and I know it's writing to the variables.cfg. it has a filter time of 4007 but won't increase.

**Comment by Clank50AE** [comment]
[klippy.log](https://github.com/user-attachments/files/16104879/klippy.log)

It doesn't look like the variable is being called during the print. Not sure tbh.

**Comment by Clank50AE** [comment]
I added a line in the macro that sends a "Air Filter time saved" to the console. It ran every second, so it seems to be working. I removed that line and restarted Klipper. It appears to be working correctly after that. Thank you for your time.
